/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dowell_zanowalletlib_PlainWalletApi */

#ifndef _Included_com_dowell_zanowalletlib_PlainWalletApi
#define _Included_com_dowell_zanowalletlib_PlainWalletApi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dowell_zanowalletlib_PlainWalletApi
 * Method:    init
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dowell_zanowalletlib_PlainWalletApi_init
  (JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     com_dowell_zanowalletlib_PlainWalletApi
 * Method:    initWithIp
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dowell_zanowalletlib_PlainWalletApi_initWithIp
  (JNIEnv *, jobject, jstring, jstring, jstring, jint);

/*
 * Class:     com_dowell_zanowalletlib_PlainWalletApi
 * Method:    reset
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dowell_zanowalletlib_PlainWalletApi_reset
  (JNIEnv *, jobject);

/*
 * Class:     com_dowell_zanowalletlib_PlainWalletApi
 * Method:    setLogLevel
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dowell_zanowalletlib_PlainWalletApi_setLogLevel
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_dowell_zanowalletlib_PlainWalletApi
 * Method:    getVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dowell_zanowalletlib_PlainWalletApi_getVersion
  (JNIEnv *, jobject);

/*
 * Class:     com_dowell_zanowalletlib_PlainWalletApi
 * Method:    getWalletFiles
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dowell_zanowalletlib_PlainWalletApi_getWalletFiles
  (JNIEnv *, jobject);

/*
 * Class:     com_dowell_zanowalletlib_PlainWalletApi
 * Method:    getExportPrivateInfo
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dowell_zanowalletlib_PlainWalletApi_getExportPrivateInfo
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_dowell_zanowalletlib_PlainWalletApi
 * Method:    deleteWallet
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dowell_zanowalletlib_PlainWalletApi_deleteWallet
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_dowell_zanowalletlib_PlainWalletApi
 * Method:    getAddressInfo
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dowell_zanowalletlib_PlainWalletApi_getAddressInfo
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_dowell_zanowalletlib_PlainWalletApi
 * Method:    getAppConfig
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dowell_zanowalletlib_PlainWalletApi_getAppConfig
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_dowell_zanowalletlib_PlainWalletApi
 * Method:    setAppConfig
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dowell_zanowalletlib_PlainWalletApi_setAppConfig
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_dowell_zanowalletlib_PlainWalletApi
 * Method:    generateRandomKey
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dowell_zanowalletlib_PlainWalletApi_generateRandomKey
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dowell_zanowalletlib_PlainWalletApi
 * Method:    getLogsBuffer
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dowell_zanowalletlib_PlainWalletApi_getLogsBuffer
  (JNIEnv *, jobject);

/*
 * Class:     com_dowell_zanowalletlib_PlainWalletApi
 * Method:    truncateLog
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dowell_zanowalletlib_PlainWalletApi_truncateLog
  (JNIEnv *, jobject);

/*
 * Class:     com_dowell_zanowalletlib_PlainWalletApi
 * Method:    getConnectivityStatus
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dowell_zanowalletlib_PlainWalletApi_getConnectivityStatus
  (JNIEnv *, jobject);

/*
 * Class:     com_dowell_zanowalletlib_PlainWalletApi
 * Method:    open
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dowell_zanowalletlib_PlainWalletApi_open
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_dowell_zanowalletlib_PlainWalletApi
 * Method:    restore
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dowell_zanowalletlib_PlainWalletApi_restore
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

/*
 * Class:     com_dowell_zanowalletlib_PlainWalletApi
 * Method:    generate
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dowell_zanowalletlib_PlainWalletApi_generate
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_dowell_zanowalletlib_PlainWalletApi
 * Method:    getOpenedWallets
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dowell_zanowalletlib_PlainWalletApi_getOpenedWallets
  (JNIEnv *, jobject);

/*
 * Class:     com_dowell_zanowalletlib_PlainWalletApi
 * Method:    getWalletStatus
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dowell_zanowalletlib_PlainWalletApi_getWalletStatus
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dowell_zanowalletlib_PlainWalletApi
 * Method:    closeWallet
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dowell_zanowalletlib_PlainWalletApi_closeWallet
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dowell_zanowalletlib_PlainWalletApi
 * Method:    invoke
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dowell_zanowalletlib_PlainWalletApi_invoke
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_dowell_zanowalletlib_PlainWalletApi
 * Method:    asyncCall
 * Signature: (Ljava/lang/String;JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dowell_zanowalletlib_PlainWalletApi_asyncCall
  (JNIEnv *, jobject, jstring, jlong, jstring);

/*
 * Class:     com_dowell_zanowalletlib_PlainWalletApi
 * Method:    tryPullResult
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dowell_zanowalletlib_PlainWalletApi_tryPullResult
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dowell_zanowalletlib_PlainWalletApi
 * Method:    syncCall
 * Signature: (Ljava/lang/String;JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dowell_zanowalletlib_PlainWalletApi_syncCall
  (JNIEnv *, jobject, jstring, jlong, jstring);

/*
 * Class:     com_dowell_zanowalletlib_PlainWalletApi
 * Method:    isWalletExist
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_dowell_zanowalletlib_PlainWalletApi_isWalletExist
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_dowell_zanowalletlib_PlainWalletApi
 * Method:    getWalletInfo
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dowell_zanowalletlib_PlainWalletApi_getWalletInfo
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dowell_zanowalletlib_PlainWalletApi
 * Method:    resetWalletPassword
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dowell_zanowalletlib_PlainWalletApi_resetWalletPassword
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_dowell_zanowalletlib_PlainWalletApi
 * Method:    getCurrentTxFee
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_dowell_zanowalletlib_PlainWalletApi_getCurrentTxFee
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
